#!/bin/bash

i=1

while [ $i -le 254 ]

do #echo -n $i


    if 
	arping2 -c 1  10.0.0.$i | grep bytes >> /dev/null
    then
	arping2 -c 1 10.0.0.$i | grep bytes >>a10y.txt
	echo $i "zanyit"
    else
	echo  $i "svobodnen" >> a10y.txt
	echo $i "svoboden"
    fi


i=$[$i+1]

done
	  