#!/bin/bash


for i in 1 2 3 4 5 6 7 8 9 10 


do 

    if 
    arping2 -c 1 10.0.0.$i | grep bytes >> /dev/null
    then
    arping2 -c 1 10.0.0.$i | grep bytes >> test1
    
    else
    echo  10.0.0.$i "свободен" >> test1
    fi


done
	  