#!/bin/bash

    if

    ps -ax | grep cycle |grep froot   >> /dev/null

    then
#    /home/vova/f7/glavni
#echo "сервис работает"
date >>/root/rabotaet.txt
killall restartt
    else
    /root/froot/cycle  >> /dev/null
#echo  "перезапуск"
date >>/root/restart.txt
killall restartt

    fi


