#!/bin/bash

i=1

while [ $i -le 254 ]

do #echo -n $i


    if 
	ping -c 1  10.0.0.$i | grep 64 >> /dev/null
    then
	echo $i
	
    else
	echo "#" $i
	arping2 -c 1 10.0.0.$i | grep bytes >> net17.txt
    fi


i=$[$i+1]

done
	  