#!/bin/bash





for i in  W S E D R F T G W T R E S G F D

do

    if
    ping -c 1 172.16.5.1  >> /dev/null
    then
    echo $i
    echo  $i > /dev/ttyACM0
sleep 2

    else
    echo "что то не так"
    echo  $i >k.txt

    fi

done